services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - apps/api/.env
    depends_on:
      - database
    environment:
      - PORT=3001
      - JWT_PRIVATE_KEY_PATH=/run/secrets/jwt_private_key
      - JWT_PUBLIC_KEY_PATH=/run/secrets/jwt_public_key
      - UPLOAD_DIR=uploads
      - DATABASE_URL=postgresql://api:password@database:5432/read-n-feed?schema=public
    volumes:
      - ./uploads:/app/uploads
    secrets:
      - source: jwt_private_key
        target: jwt_private_key
      - source: jwt_public_key
        target: jwt_public_key

  database:
    container_name: read-n-feed
    image: bitnami/postgresql:16.4.0
    environment:
      POSTGRESQL_DATABASE: read-n-feed
      POSTGRESQL_USERNAME: api
      POSTGRESQL_PASSWORD: password
    volumes:
      - read_n_feed:/bitnami/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - '5432:5432'

secrets:
  jwt_private_key:
    file: apps/api/secrets/jwtRS256.key
  jwt_public_key:
    file: apps/api/secrets/jwtRS256.key.pub

volumes:
  read_n_feed:
