export enum ConfigKeys {
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXP = 'JWT_EXP',
  REFRESH_TOKEN_MAX_AGE_DAYS = 'REFRESH_TOKEN_MAX_AGE_DAYS',
  PORT = 'PORT',
  NODE_ENV = 'NODE_ENV',
  DATABASE = 'DATABASE',
  FRONTEND_URL = 'FRONTEND_URL',
  PINO_LOG_LEVEL = 'PINO_LOG_LEVEL',
}
