export const QueryKey = {
  GetProfile: 'get-profile',
  GetBooksCatalog: 'get-books-catalog',
  GetBookById: 'get-book-by-id',
  GetMyBookRequests: 'get-my-requests',
  GetAdminBookRequests: 'get-admin-requests',
  GetBookRequestById: 'get-request-by-id',
  GetBookFiles: 'get-book-files',
  GetBookRequestFiles: 'get-book-request-files',
  GetMyFileRequests: 'get-my-file-requests',
  GetAdminFileRequests: 'get-admin-file-requests',
  GetFileRequestById: 'get-file-request-by-id',
  DownloadUrl: 'download-url',
  Metadata: 'metadata',
  Recommendations: 'recommendations',
};
