name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-npm-${{ hashFiles('**/yarn.lock') }}
      - name: Prepare Yarn
        run: corepack prepare yarn@4.6.0 --activate
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4
      - run: yarn nx affected -t lint test build
